// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVJacwsc69Frzd8gjzP9kkl_hGiC4YME',
    appId: '1:416833184658:web:4b24c2987a3056ca0bd74b',
    messagingSenderId: '416833184658',
    projectId: 'hiwar-marifa',
    authDomain: 'hiwar-marifa.firebaseapp.com',
    storageBucket: 'hiwar-marifa.firebasestorage.app',
    measurementId: 'G-2094YQMLBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2l99c6BteBpMzbPF_d8wnvsc_VjsTfaI',
    appId: '1:416833184658:android:f83b294325a15f150bd74b',
    messagingSenderId: '416833184658',
    projectId: 'hiwar-marifa',
    storageBucket: 'hiwar-marifa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkLLwYyGH4FiD9if2583_WzWCzyqj7tSA',
    appId: '1:416833184658:ios:d52771bcd809fb1d0bd74b',
    messagingSenderId: '416833184658',
    projectId: 'hiwar-marifa',
    storageBucket: 'hiwar-marifa.firebasestorage.app',
    iosBundleId: 'com.example.hiwarMarifa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkLLwYyGH4FiD9if2583_WzWCzyqj7tSA',
    appId: '1:416833184658:ios:d52771bcd809fb1d0bd74b',
    messagingSenderId: '416833184658',
    projectId: 'hiwar-marifa',
    storageBucket: 'hiwar-marifa.firebasestorage.app',
    iosBundleId: 'com.example.hiwarMarifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMVJacwsc69Frzd8gjzP9kkl_hGiC4YME',
    appId: '1:416833184658:web:170e5b2f8e816f6a0bd74b',
    messagingSenderId: '416833184658',
    projectId: 'hiwar-marifa',
    authDomain: 'hiwar-marifa.firebaseapp.com',
    storageBucket: 'hiwar-marifa.firebasestorage.app',
    measurementId: 'G-1EYXXFGKQ0',
  );
}
